const GRAPH_DATA={nodes:[
// === ./src ===
{id:"AppEntry",label:"AppEntry.tsx",group:"entry",path:"src/AppEntry.tsx",lines:17,type:"component"},
{id:"theme",label:"theme/index.ts",group:"appTheme",path:"src/theme/index.ts",lines:76,type:"config"},
{id:"MainStack",label:"MainStack.tsx",group:"routes",path:"src/routes/MainStack.tsx",lines:37,type:"component"},
{id:"BottomStack",label:"BottomStack.tsx",group:"routes",path:"src/routes/BottomStack.tsx",lines:75,type:"component"},
{id:"TabIcon",label:"TabIcon.tsx",group:"routes",path:"src/routes/components/TabIcon.tsx",lines:103,type:"component"},
{id:"routeTypes",label:"types/index.ts",group:"routes",path:"src/routes/types/index.ts",lines:24,type:"types"},
{id:"useCartStore",label:"useCartStore.ts",group:"store",path:"src/store/cart/useCartStore.ts",lines:72,type:"hook"},
{id:"cartTypes",label:"cart/types.ts",group:"store",path:"src/store/cart/types.ts",lines:19,type:"types"},
{id:"HomeIndex",label:"Home/index.ts",group:"home",path:"src/screens/Home/index.ts",lines:6,type:"barrel"},
{id:"HomeScreen",label:"HomeScreen.tsx",group:"home",path:"src/screens/Home/HomeScreen.tsx",lines:132,type:"screen"},
{id:"Header",label:"Header.tsx",group:"home",path:"src/screens/Home/components/Header.tsx",lines:121,type:"component"},
{id:"BannerCarousel",label:"BannerCarousel.tsx",group:"home",path:"src/screens/Home/components/BannerCarousel.tsx",lines:143,type:"component"},
{id:"CategoryRow",label:"CategoryRow.tsx",group:"home",path:"src/screens/Home/components/CategoryRow.tsx",lines:86,type:"component"},
{id:"ProductCard",label:"ProductCard.tsx",group:"home",path:"src/screens/Home/components/ProductCard.tsx",lines:220,type:"component"},
{id:"ProductGrid",label:"ProductGrid.tsx",group:"home",path:"src/screens/Home/components/ProductGrid.tsx",lines:34,type:"component"},
{id:"PromoBanners",label:"PromoBanners.tsx",group:"home",path:"src/screens/Home/components/PromoBanners.tsx",lines:79,type:"component"},
{id:"PromoVideoSection",label:"PromoVideoSection.tsx",group:"home",path:"src/screens/Home/components/PromoVideoSection.tsx",lines:126,type:"component"},
{id:"PromoVideoCarousel",label:"PromoVideoCarousel.tsx",group:"home",path:"src/screens/Home/components/PromoVideoCarousel.tsx",lines:196,type:"component"},
{id:"SectionHeader",label:"SectionHeader.tsx",group:"home",path:"src/screens/Home/components/SectionHeader.tsx",lines:54,type:"component"},
{id:"ShopCTA",label:"ShopCTA.tsx",group:"home",path:"src/screens/Home/components/ShopCTA.tsx",lines:57,type:"component"},
{id:"useHomeData",label:"useHomeData.ts",group:"home",path:"src/screens/Home/hooks/useHomeData.ts",lines:113,type:"hook"},
{id:"useHomeSections",label:"useHomeSections.ts",group:"home",path:"src/screens/Home/hooks/useHomeSections.ts",lines:155,type:"hook"},
{id:"useBannerCarousel",label:"useBannerCarousel.ts",group:"home",path:"src/screens/Home/hooks/useBannerCarousel.ts",lines:36,type:"hook"},
{id:"useResponsiveGrid",label:"useResponsiveGrid.ts",group:"home",path:"src/screens/Home/hooks/useResponsiveGrid.ts",lines:31,type:"hook"},
{id:"CartScreen",label:"Cart/index.tsx",group:"cart",path:"src/screens/Cart/index.tsx",lines:90,type:"screen"},
{id:"CartItemCard",label:"CartItemCard.tsx",group:"cart",path:"src/screens/Cart/components/CartItemCard.tsx",lines:141,type:"component"},
{id:"CartSummary",label:"CartSummary.tsx",group:"cart",path:"src/screens/Cart/components/CartSummary.tsx",lines:105,type:"component"},
{id:"EmptyCart",label:"EmptyCart.tsx",group:"cart",path:"src/screens/Cart/components/EmptyCart.tsx",lines:39,type:"component"},
{id:"useCartScreen",label:"useCartScreen.ts",group:"cart",path:"src/screens/Cart/hooks/useCartScreen.ts",lines:23,type:"hook"},
{id:"GrooveScreen",label:"Groove/index.tsx",group:"groove",path:"src/screens/Groove/index.tsx",lines:39,type:"screen"},
{id:"GrooveHero",label:"GrooveHero.tsx",group:"groove",path:"src/screens/Groove/components/GrooveHero.tsx",lines:80,type:"component"},
{id:"MoodStrip",label:"MoodStrip.tsx",group:"groove",path:"src/screens/Groove/components/MoodStrip.tsx",lines:73,type:"component"},
{id:"ShopTheLook",label:"ShopTheLook.tsx",group:"groove",path:"src/screens/Groove/components/ShopTheLook.tsx",lines:126,type:"component"},
{id:"EditorialBanners",label:"EditorialBanners.tsx",group:"groove",path:"src/screens/Groove/components/EditorialBanners.tsx",lines:83,type:"component"},
{id:"GrooveGrid",label:"GrooveGrid.tsx",group:"groove",path:"src/screens/Groove/components/GrooveGrid.tsx",lines:162,type:"component"},
{id:"useGrooveData",label:"useGrooveData.ts",group:"groove",path:"src/screens/Groove/hooks/useGrooveData.ts",lines:45,type:"hook"},
{id:"useGrooveLayout",label:"useGrooveLayout.ts",group:"groove",path:"src/screens/Groove/hooks/useGrooveLayout.ts",lines:39,type:"hook"},
{id:"PDIndex",label:"ProductDetails/index.ts",group:"productdetails",path:"src/screens/ProductDetails/index.ts",lines:2,type:"barrel"},
{id:"ProductDetailsScreen",label:"ProductDetailsScreen.tsx",group:"productdetails",path:"src/screens/ProductDetails/ProductDetailsScreen.tsx",lines:133,type:"screen"},
{id:"ImageCarousel",label:"ImageCarousel.tsx",group:"productdetails",path:"src/screens/ProductDetails/components/ImageCarousel.tsx",lines:78,type:"component"},
{id:"ProductInfo",label:"ProductInfo.tsx",group:"productdetails",path:"src/screens/ProductDetails/components/ProductInfo.tsx",lines:94,type:"component"},
{id:"SizeSelector",label:"SizeSelector.tsx",group:"productdetails",path:"src/screens/ProductDetails/components/SizeSelector.tsx",lines:95,type:"component"},
{id:"ColorSelector",label:"ColorSelector.tsx",group:"productdetails",path:"src/screens/ProductDetails/components/ColorSelector.tsx",lines:70,type:"component"},
{id:"ProductDescription",label:"ProductDescription.tsx",group:"productdetails",path:"src/screens/ProductDetails/components/ProductDescription.tsx",lines:50,type:"component"},
{id:"BottomCTA",label:"BottomCTA.tsx",group:"productdetails",path:"src/screens/ProductDetails/components/BottomCTA.tsx",lines:55,type:"component"},
{id:"useProductDetails",label:"useProductDetails.ts",group:"productdetails",path:"src/screens/ProductDetails/hooks/useProductDetails.ts",lines:82,type:"hook"},
// === ./package ===
{id:"pkgIndex",label:"index.ts",group:"pkgEntry",path:"package/src/index.ts",lines:61,type:"barrel"},
{id:"pkgTypes",label:"types/index.ts",group:"pkgTypes",path:"package/src/types/index.ts",lines:76,type:"types"},
{id:"colorTypes",label:"colors/types.ts",group:"pkgColors",path:"package/src/colors/types.ts",lines:5,type:"types"},
{id:"colorIndex",label:"colors/index.ts",group:"pkgColors",path:"package/src/colors/index.ts",lines:3,type:"barrel"},
{id:"buildColorScaleMap",label:"buildColorScaleMap.ts",group:"pkgColors",path:"package/src/colors/buildColorScaleMap.ts",lines:8,type:"util"},
{id:"fontsIndex",label:"fonts/index.ts",group:"pkgFonts",path:"package/src/fonts/index.ts",lines:18,type:"barrel"},
{id:"createFontConfig",label:"createFontConfig.ts",group:"pkgFonts",path:"package/src/fonts/createFontConfig.ts",lines:119,type:"util"},
{id:"fontTypes",label:"fonts/types.ts",group:"pkgFonts",path:"package/src/fonts/types.ts",lines:60,type:"types"},
{id:"providerIndex",label:"provider/index.ts",group:"pkgProvider",path:"package/src/provider/index.ts",lines:16,type:"barrel"},
{id:"ThemeProvider",label:"ThemeProvider.tsx",group:"pkgProvider",path:"package/src/provider/ThemeProvider.tsx",lines:41,type:"component"},
{id:"ThemeContext",label:"ThemeContext.ts",group:"pkgProvider",path:"package/src/provider/ThemeContext.ts",lines:14,type:"config"},
{id:"createThemeKit",label:"createThemeKit.ts",group:"pkgProvider",path:"package/src/provider/createThemeKit.ts",lines:47,type:"util"},
{id:"provHooksIndex",label:"hooks/index.ts",group:"pkgProvider",path:"package/src/provider/hooks/index.ts",lines:7,type:"barrel"},
{id:"pkgUseTheme",label:"useTheme.ts",group:"pkgProvider",path:"package/src/provider/hooks/useTheme.ts",lines:17,type:"hook"},
{id:"useThemeMode",label:"useThemeMode.ts",group:"pkgProvider",path:"package/src/provider/hooks/useThemeMode.ts",lines:56,type:"hook"},
{id:"useComposedTheme",label:"useComposedTheme.ts",group:"pkgProvider",path:"package/src/provider/hooks/useComposedTheme.ts",lines:24,type:"hook"},
{id:"useLayoutState",label:"useLayoutState.ts",group:"pkgProvider",path:"package/src/provider/hooks/useLayoutState.ts",lines:28,type:"hook"},
{id:"useAccessibilityState",label:"useAccessibilityState.ts",group:"pkgProvider",path:"package/src/provider/hooks/useAccessibilityState.ts",lines:20,type:"hook"},
{id:"themeIndex",label:"theme/index.ts",group:"pkgTheme",path:"package/src/theme/index.ts",lines:20,type:"barrel"},
{id:"createProjectTheme",label:"createProjectTheme.ts",group:"pkgTheme",path:"package/src/theme/createProjectTheme.ts",lines:71,type:"util"},
{id:"themeCache",label:"themeCache.ts",group:"pkgTheme",path:"package/src/theme/themeCache.ts",lines:4,type:"util"},
{id:"themeTypesRe",label:"theme/types.ts",group:"pkgTheme",path:"package/src/theme/types.ts",lines:13,type:"types"},
{id:"stylesIndex",label:"styles/index.ts",group:"pkgStyles",path:"package/src/styles/index.ts",lines:3,type:"barrel"},
{id:"createStylesFn",label:"createStyles.ts",group:"pkgStyles",path:"package/src/styles/createStyles.ts",lines:83,type:"util"},
{id:"createShadow",label:"createShadow.ts",group:"pkgShadows",path:"package/src/shadows/createShadow.ts",lines:19,type:"util"},
{id:"createShadowScale",label:"createShadowScale.ts",group:"pkgShadows",path:"package/src/shadows/createShadowScale.ts",lines:20,type:"util"},
{id:"shadowCache",label:"shadowCache.ts",group:"pkgShadows",path:"package/src/shadows/shadowCache.ts",lines:13,type:"util"},
{id:"utilsIndex",label:"utils/index.ts",group:"pkgUtils",path:"package/src/utils/index.ts",lines:5,type:"barrel"},
{id:"scaling",label:"layout/scaling.ts",group:"pkgUtils",path:"package/src/utils/layout/scaling.ts",lines:65,type:"util"},
{id:"accessibility",label:"accessibility.ts",group:"pkgUtils",path:"package/src/utils/accessibility/accessibility.ts",lines:55,type:"util"},
{id:"tokenColors",label:"tokens/colors.ts",group:"pkgTokens",path:"package/src/tokens/colors.ts",lines:36,type:"config"},
{id:"tokenSpacing",label:"tokens/spacing.ts",group:"pkgTokens",path:"package/src/tokens/spacing.ts",lines:11,type:"config"},
{id:"tokenRadius",label:"tokens/radius.ts",group:"pkgTokens",path:"package/src/tokens/radius.ts",lines:10,type:"config"},
{id:"tokenShadows",label:"tokens/shadows.ts",group:"pkgTokens",path:"package/src/tokens/shadows.ts",lines:11,type:"config"},
],edges:[
// === ./src edges ===
{from:"AppEntry",to:"theme",label:"projectTheme"},{from:"AppEntry",to:"MainStack",label:"renders"},
{from:"MainStack",to:"BottomStack",label:"screen"},{from:"MainStack",to:"routeTypes",label:"types"},{from:"MainStack",to:"PDIndex",label:"screen"},
{from:"BottomStack",to:"theme",label:"useTheme"},{from:"BottomStack",to:"HomeIndex",label:"screen"},{from:"BottomStack",to:"CartScreen",label:"screen"},{from:"BottomStack",to:"GrooveScreen",label:"screen"},{from:"BottomStack",to:"routeTypes",label:"types"},{from:"BottomStack",to:"TabIcon",label:"renders"},{from:"BottomStack",to:"useCartStore",label:"selector"},
{from:"TabIcon",to:"theme",label:"styles"},{from:"useCartStore",to:"cartTypes",label:"types"},
{from:"HomeIndex",to:"HomeScreen",label:"re-export"},{from:"HomeIndex",to:"useHomeData",label:"re-export types"},{from:"HomeIndex",to:"useHomeSections",label:"re-export types"},{from:"HomeIndex",to:"PromoVideoSection",label:"re-export"},{from:"HomeIndex",to:"PromoVideoCarousel",label:"re-export"},
{from:"HomeScreen",to:"useHomeSections",label:"data+viewability"},{from:"HomeScreen",to:"Header",label:"renders"},{from:"HomeScreen",to:"BannerCarousel",label:"renders"},{from:"HomeScreen",to:"CategoryRow",label:"renders"},{from:"HomeScreen",to:"PromoBanners",label:"renders"},{from:"HomeScreen",to:"ProductGrid",label:"renders"},{from:"HomeScreen",to:"SectionHeader",label:"renders"},{from:"HomeScreen",to:"ShopCTA",label:"renders"},{from:"HomeScreen",to:"PromoVideoCarousel",label:"renders"},{from:"HomeScreen",to:"PromoVideoSection",label:"renders"},
{from:"PromoVideoCarousel",to:"PromoVideoSection",label:"renders"},{from:"PromoVideoCarousel",to:"theme",label:"createStyles"},
{from:"useHomeSections",to:"useHomeData",label:"data+types"},
{from:"PromoVideoSection",to:"theme",label:"createStyles"},
{from:"Header",to:"theme",label:"styles"},{from:"Header",to:"routeTypes",label:"types"},{from:"Header",to:"useCartStore",label:"selector"},
{from:"BannerCarousel",to:"theme",label:"styles"},{from:"BannerCarousel",to:"useHomeData",label:"type"},{from:"BannerCarousel",to:"useBannerCarousel",label:"hook"},{from:"BannerCarousel",to:"useResponsiveGrid",label:"hook"},
{from:"CategoryRow",to:"theme",label:"styles"},{from:"CategoryRow",to:"useHomeData",label:"type"},
{from:"ProductCard",to:"theme",label:"styles"},{from:"ProductCard",to:"useHomeData",label:"type"},{from:"ProductCard",to:"useCartStore",label:"store"},{from:"ProductCard",to:"routeTypes",label:"types"},
{from:"ProductGrid",to:"useHomeData",label:"type"},{from:"ProductGrid",to:"ProductCard",label:"renders"},{from:"ProductGrid",to:"useResponsiveGrid",label:"hook"},
{from:"PromoBanners",to:"theme",label:"styles"},{from:"PromoBanners",to:"useHomeData",label:"type"},{from:"PromoBanners",to:"useResponsiveGrid",label:"hook"},
{from:"SectionHeader",to:"theme",label:"styles"},{from:"ShopCTA",to:"theme",label:"styles"},
{from:"useBannerCarousel",to:"theme",label:"useTheme"},{from:"useResponsiveGrid",to:"theme",label:"useTheme"},
{from:"CartScreen",to:"theme",label:"styles"},{from:"CartScreen",to:"useCartScreen",label:"hook"},{from:"CartScreen",to:"CartItemCard",label:"renders"},{from:"CartScreen",to:"CartSummary",label:"renders"},{from:"CartScreen",to:"EmptyCart",label:"renders"},
{from:"CartItemCard",to:"theme",label:"styles"},{from:"CartSummary",to:"theme",label:"styles"},{from:"EmptyCart",to:"theme",label:"styles"},
{from:"useCartScreen",to:"useCartStore",label:"store"},
{from:"GrooveScreen",to:"theme",label:"styles"},{from:"GrooveScreen",to:"useGrooveData",label:"data"},{from:"GrooveScreen",to:"GrooveHero",label:"renders"},{from:"GrooveScreen",to:"MoodStrip",label:"renders"},{from:"GrooveScreen",to:"ShopTheLook",label:"renders"},{from:"GrooveScreen",to:"EditorialBanners",label:"renders"},{from:"GrooveScreen",to:"GrooveGrid",label:"renders"},
{from:"GrooveHero",to:"theme",label:"styles"},{from:"GrooveHero",to:"useGrooveLayout",label:"hook"},
{from:"MoodStrip",to:"theme",label:"styles"},{from:"MoodStrip",to:"useGrooveData",label:"type"},{from:"MoodStrip",to:"useGrooveLayout",label:"hook"},
{from:"ShopTheLook",to:"theme",label:"styles"},{from:"ShopTheLook",to:"useGrooveData",label:"type"},{from:"ShopTheLook",to:"useGrooveLayout",label:"hook"},
{from:"EditorialBanners",to:"theme",label:"styles"},{from:"EditorialBanners",to:"useGrooveData",label:"type"},{from:"EditorialBanners",to:"useGrooveLayout",label:"hook"},
{from:"GrooveGrid",to:"theme",label:"styles"},{from:"GrooveGrid",to:"useGrooveData",label:"type"},{from:"GrooveGrid",to:"useGrooveLayout",label:"hook"},
{from:"useGrooveLayout",to:"theme",label:"useTheme"},
{from:"PDIndex",to:"ProductDetailsScreen",label:"re-export"},
{from:"ProductDetailsScreen",to:"useProductDetails",label:"hook"},{from:"ProductDetailsScreen",to:"ImageCarousel",label:"renders"},{from:"ProductDetailsScreen",to:"ProductInfo",label:"renders"},{from:"ProductDetailsScreen",to:"SizeSelector",label:"renders"},{from:"ProductDetailsScreen",to:"ColorSelector",label:"renders"},{from:"ProductDetailsScreen",to:"ProductDescription",label:"renders"},{from:"ProductDetailsScreen",to:"BottomCTA",label:"renders"},{from:"ProductDetailsScreen",to:"useCartStore",label:"store"},{from:"ProductDetailsScreen",to:"useHomeData",label:"type"},{from:"ProductDetailsScreen",to:"theme",label:"styles"},
{from:"ImageCarousel",to:"theme",label:"styles"},{from:"ProductInfo",to:"theme",label:"styles"},{from:"SizeSelector",to:"theme",label:"styles"},{from:"ColorSelector",to:"theme",label:"styles"},{from:"ProductDescription",to:"theme",label:"styles"},{from:"BottomCTA",to:"theme",label:"styles"},
// === ./package edges ===
{from:"pkgIndex",to:"themeIndex",label:"re-export"},{from:"pkgIndex",to:"providerIndex",label:"re-export"},{from:"pkgIndex",to:"stylesIndex",label:"re-export"},{from:"pkgIndex",to:"fontsIndex",label:"re-export"},{from:"pkgIndex",to:"utilsIndex",label:"re-export"},{from:"pkgIndex",to:"colorIndex",label:"re-export"},
{from:"providerIndex",to:"ThemeProvider",label:"re-export"},{from:"providerIndex",to:"ThemeContext",label:"re-export"},{from:"providerIndex",to:"createThemeKit",label:"re-export"},{from:"providerIndex",to:"pkgUseTheme",label:"re-export"},{from:"providerIndex",to:"useThemeMode",label:"re-export"},{from:"providerIndex",to:"useLayoutState",label:"re-export"},{from:"providerIndex",to:"useAccessibilityState",label:"re-export"},{from:"providerIndex",to:"useComposedTheme",label:"re-export"},
{from:"ThemeProvider",to:"pkgTypes",label:"types"},{from:"ThemeProvider",to:"ThemeContext",label:"context"},{from:"ThemeProvider",to:"useThemeMode",label:"hook"},{from:"ThemeProvider",to:"useLayoutState",label:"hook"},{from:"ThemeProvider",to:"useAccessibilityState",label:"hook"},{from:"ThemeProvider",to:"useComposedTheme",label:"hook"},
{from:"ThemeContext",to:"pkgTypes",label:"types"},
{from:"createThemeKit",to:"ThemeContext",label:"context"},{from:"createThemeKit",to:"pkgTypes",label:"types"},{from:"createThemeKit",to:"createStylesFn",label:"makeCreateStyles"},
{from:"pkgUseTheme",to:"pkgTypes",label:"types"},{from:"pkgUseTheme",to:"ThemeContext",label:"context"},
{from:"useComposedTheme",to:"pkgTypes",label:"types"},{from:"useComposedTheme",to:"accessibility",label:"buildA11yInfo"},{from:"useComposedTheme",to:"scaling",label:"resolveResponsive"},
{from:"useLayoutState",to:"scaling",label:"buildLayoutInfo"},
{from:"useAccessibilityState",to:"accessibility",label:"readSnapshot"},
{from:"themeIndex",to:"createProjectTheme",label:"re-export"},{from:"themeIndex",to:"createShadow",label:"re-export"},{from:"themeIndex",to:"createShadowScale",label:"re-export"},{from:"themeIndex",to:"shadowCache",label:"re-export"},{from:"themeIndex",to:"tokenColors",label:"re-export"},{from:"themeIndex",to:"pkgTypes",label:"types"},
{from:"themeTypesRe",to:"pkgTypes",label:"re-export types"},
{from:"createProjectTheme",to:"pkgTypes",label:"types"},{from:"createProjectTheme",to:"tokenSpacing",label:"defaults"},{from:"createProjectTheme",to:"tokenRadius",label:"defaults"},{from:"createProjectTheme",to:"tokenColors",label:"baseColors"},{from:"createProjectTheme",to:"shadowCache",label:"getShadowScale"},{from:"createProjectTheme",to:"buildColorScaleMap",label:"builds"},{from:"createProjectTheme",to:"themeCache",label:"cache"},
{from:"stylesIndex",to:"createStylesFn",label:"re-export"},
{from:"createStylesFn",to:"pkgTypes",label:"types"},{from:"createStylesFn",to:"ThemeContext",label:"context"},
{from:"fontsIndex",to:"createFontConfig",label:"re-export"},{from:"fontsIndex",to:"fontTypes",label:"types"},
{from:"createFontConfig",to:"fontTypes",label:"types"},
{from:"colorIndex",to:"buildColorScaleMap",label:"re-export"},{from:"colorIndex",to:"colorTypes",label:"types"},
{from:"buildColorScaleMap",to:"colorTypes",label:"types"},
{from:"utilsIndex",to:"scaling",label:"re-export"},{from:"utilsIndex",to:"accessibility",label:"re-export"},
{from:"createShadow",to:"pkgTypes",label:"types"},
{from:"createShadowScale",to:"pkgTypes",label:"types"},{from:"createShadowScale",to:"tokenShadows",label:"levels"},{from:"createShadowScale",to:"createShadow",label:"creates"},
{from:"shadowCache",to:"pkgTypes",label:"types"},{from:"shadowCache",to:"createShadowScale",label:"creates"},
{from:"tokenSpacing",to:"pkgTypes",label:"types"},{from:"tokenRadius",to:"pkgTypes",label:"types"},{from:"tokenShadows",to:"pkgTypes",label:"types"},
{from:"pkgTypes",to:"colorTypes",label:"types"},{from:"pkgTypes",to:"tokenColors",label:"BaseColors"},{from:"pkgTypes",to:"utilsIndex",label:"LayoutInfo, A11yInfo"},
{from:"themeCache",to:"pkgTypes",label:"types"},
// === Cross-boundary (src → package) ===
{from:"theme",to:"pkgIndex",label:"@rohit-dev/design-system",cross:true},
{from:"AppEntry",to:"pkgIndex",label:"ThemeProvider",cross:true},
{from:"HomeScreen",to:"pkgIndex",label:"useTheme+createStyles",cross:true},
{from:"PromoVideoSection",to:"pkgIndex",label:"createStyles",cross:true},
{from:"PromoVideoCarousel",to:"pkgIndex",label:"createStyles",cross:true},
],
groups:{
  entry:{label:"App Entry",color:"#FF6B35"},appTheme:{label:"App Theme Config",color:"#F59E0B"},
  routes:{label:"Navigation",color:"#2563EB"},store:{label:"State (Zustand)",color:"#DC2626"},
  home:{label:"Home Screen",color:"#059669"},cart:{label:"Cart Screen",color:"#D97706"},
  groove:{label:"Groove Screen",color:"#EC4899"},productdetails:{label:"Product Details",color:"#0891B2"},
  pkgEntry:{label:"📦 Package Entry",color:"#A855F7"},pkgTypes:{label:"📦 Core Types",color:"#6366F1"},
  pkgColors:{label:"📦 Colors",color:"#F43F5E"},pkgFonts:{label:"📦 Fonts",color:"#14B8A6"},
  pkgProvider:{label:"📦 Provider",color:"#8B5CF6"},pkgTheme:{label:"📦 Theme Builder",color:"#7C3AED"},
  pkgStyles:{label:"📦 Styles",color:"#06B6D4"},pkgShadows:{label:"📦 Shadows",color:"#64748B"},
  pkgUtils:{label:"📦 Utils",color:"#22C55E"},pkgTokens:{label:"📦 Design Tokens",color:"#EAB308"},
},
stats:{totalFiles:80,totalLines:4800,screens:4,components:25,hooks:16,types:6,utils:10,barrels:10}
};
